### ISSUE TITLE
Better error handling 

### ISSUE THREAD

**Issue by praveenperera** [elixir-grpc/grpc#170]
I think the error handling good be improved a little bit. Instead of always returning the same `RPCError` struct we could pattern match on the status code and return different errors. Currently I'm doing it like below. If you like this approach I could do a PR:

```elixir
defmodule Bossman.Job.Error do
  defmodule NotFound, do: defexception([:message])
  defmodule Unknown, do: defexception([:message])
  defmodule InvalidArgument, do: defexception([:message])

  def new(%GRPC.RPCError{message: message, status: status}) do
    status_to_error_struct(status, URI.decode(message))
  end

  defp status_to_error_struct(2, msg), do: %Unknown{message: msg}
  defp status_to_error_struct(3, msg), do: %InvalidArgument{message: msg}
  defp status_to_error_struct(5, msg), do: %NotFound{message: msg}
end
```

**Comment by polvalente** [comment]
@praveenperera would you still like to contribute with this?

I think this approach is good and we can accompany it with a `is_rpc_error` guard so users can still match in a generic manner wherever needed.

**Comment by polvalente** [comment]
Another possible solution is to just document the status atoms better

**Comment by hackvan** [comment]
> Another possible solution is to just document the status atoms better

Hi @polvalente,

Do you think its enough adding an ASCII table in the `@moduledoc` like this:

| Error  |       Status           |                                             Status Message                                            |
|--------:|------------------------|-------------------------------------------------------------------------------------------------------|
|     0  |  "OK"                  |                                                                                                       |
|     1  |  "Canceled"            |  "The operation was cancelled (typically by the caller)"                                              |
|     2  |  "Unknown"             |  "Unknown error"                                                                                      |
|     3  |  "InvalidArgument"     |  "Client specified an invalid argument"                                                               |
|     4  |  "DeadlineExceeded"    |  "Deadline expired before operation could complete"                                                   |
|     5  |  "NotFound"            |  "Some requested entity (e.g., file or directory) was not found"                                      |
|     6  |  "AlreadyExists"       |  "Some entity that we attempted to create (e.g., file or directory) already exists"                   |
|     7  |  "PermissionDenied"    |  "The caller does not have permission to execute the specified operation"                             |
|     8  |  "ResourceExhausted"   |  "Some resource has been exhausted"                                                                   |
|     9  |  "FailedPrecondition"  |  "Operation was rejected because the system is not in a state required for the operation's execution" |
|    10  |  "Aborted"             |  "The operation was aborted"                                                                          |
|    11  |  "OutOfRange"          |  "Operation was attempted past the valid range"                                                       |
|    12  |  "Unimplemented"       |  "Operation is not implemented or not supported/enabled in this service"                              |
|    13  |  "Internal"            |  "Internal errors"                                                                                    |
|    14  |  "Unavailable"         |  "The service is currently unavailable"                                                               |
|    15  |  "DataLoss"            |  "Unrecoverable data loss or corruption"                                                              |
|    16  |  "Unauthenticated"     |  "The request does not have valid authentication credentials for the operation"                       |

Would it be better to include it in the `GRPC.Status` module or in the `GRPC.RPCError` module?

**Comment by polvalente** [comment]
@hackvan I think that's perfect. We can put that in `GRPC.Status` and add something like "See `GRPC.Status` for more details on possible statuses" in `GRPC.Error`

**Comment by polvalente** [comment]
I think we could provide this macro in GRPC.RPCError together with the better documentation:

```elixir
defmacro is_rpc_error(e, status) when is_struct(e, GRPC.RPCError) and e.status == status
```

Which would make it easier for users to pattern match on different error types without the hassle of dealing with many different kinds of structs

**Comment by hackvan** [comment]
> That looks good, but I'd format it with a markdown table so ex doc renders it nicely.

Yeap, I did it that way:
<img width="1043" alt="image" src="https://github.com/elixir-grpc/grpc/assets/179497/62e862e2-acf0-4a79-928f-768f1430d64c">

![image](https://github.com/elixir-grpc/grpc/assets/179497/08ce9bfe-5bb8-43bb-b6be-fe18fcd2fffc)

> The guard (I wrote defmacro but should have been defguard there) covers the use case mentioned in the issue body itself, where instead of having different structs for pattern matching, we can just use the guard for matching on different errors

Ok, I get it but in this case when the people need to use the `defguard` they would need to import the `GRPC.RPCError` module first, right?

**Comment by polvalente** [comment]
Yes. Or require it. But that's a lot more manageable than aliasing N different structs
