### ISSUE TITLE
Support for alternative wire formats?

### ISSUE THREAD

**Issue by freshtonic** [elixir-grpc/grpc#207]
Currently, it seems that only Protobuf is supported as a wire format.

How coupled is this library to Protobuf and is there a plan to support alternative wire formats?

**Comment by drowzy** [comment]
Looking at [`GRPC.Message`](https://github.com/elixir-grpc/grpc/blob/master/lib/grpc/message.ex) it doesn't look like being Protobuf only since the message is encoded/decoded using the codec. I might be wrong though!

For codecs see for [instance](https://github.com/elixir-grpc/grpc/blob/master/lib/grpc/codec/erlpack.ex). 

usage:
```elixir
defmodule HelloServer do
    use GRPC.Server,
      service: Helloworld.Greeter.Service,
      codecs: [GRPC.Codec.Erlpack]
    
    def say_hello(req, _stream) do
      Helloworld.HelloReply.new(message: "Hello, #{req.name}")
    end
  end
  
  defmodule HelloStub do
    use GRPC.Stub, service: Helloworld.Greeter.Service
  end
```
```elixir
{:ok, channel} = GRPC.Stub.connect("localhost:8080")
req = Helloworld.HelloRequest.new(name: "hello")
{:ok, reply} = channel |> HelloStub.say_hello(req, codec: GRPC.Codec.Erlpack)
```
You can implement your own by implementing the [`codec`](https://github.com/elixir-grpc/grpc/blob/master/lib/grpc/codec.ex) behaviour.

Hope it helps!

**Comment by freshtonic** [comment]
Thanks @drowzy - that's great. I swear I looked at the project README and "support protocols other than Protobufs" was unchecked :)
