### ISSUE TITLE
How to use this elixir-grpc in a erlang project, do you have an example?

### ISSUE THREAD

**Issue by tclugao** [elixir-grpc/grpc#313]
**Describe the question**
as the title, we also want to introduce the "elixir-grpc" to an Erlang project (using rebar3 as deps management), do you have a example?

**Versions:**
- OS: wsl2
- Erlang: OTP 22
- Elixir: 1.13.3
- mix.lock(grpc, gun, cowboy, cowlib):

following are my tryout for add deps in erlang rebar3.config file

    {grpc,                 {git, "git@github.com:elixir-grpc/grpc.git"},                   {branch, "master"}},
    {protobuf,          {git, "git@github.com:tigertext/protobuf.git",            {branch, "lugao_v1"}}},  

protubuf is forked from  protobuf repo and there no code to modify comapred to protobuf v0.10.0, 

and then when I run rebar3 as test shell, report the following error:
**===> Failed to boot grpc for reason {"no such file or directory",
                                                "grpc.app"}
===> Failed to boot eex for reason {"no such file or directory",
                                               "eex.app"}**

**Comment by polvalente** [comment]
Unfortunately I am not familiar with rebar3 to help with this. I'm gonna leave the issue open in the hope that someone else can chime in.
Perhaps try asking about pulling Elixir dependencies in general for Erlang projects?

However, I should point out that you might need to include some Elixir source code in your project due to the heavy usage of macros in the normal interface for this lib.

**Comment by tclugao** [comment]
thank you! I have solved the problem,  the rebar plugin rebar_mix  have bug and I have fixed in my branch!  erlang toolchain is so poor, lol,  I close this issue at your convenience！
